---
Name: elementalgrid
Before:
  - 'elemental'
---
SilverStripe\Core\Manifest\ModuleManifest:
  module_priority:
    - thewebmen/silverstripe-elemental-grid
    - dnadesign/silverstripe-elemental

DNADesign\Elemental\ElementalEditor:
  extensions:
    - TheWebmen\ElementalGrid\Extensions\ElementalEditorExtension

DNADesign\Elemental\Models\BaseElement:
  extensions:
    - TheWebmen\ElementalGrid\Extensions\BaseElementExtension

DNADesign\Elemental\Models\ElementalArea:
  extensions:
    - TheWebmen\ElementalGrid\Extensions\ElementalAreaExtension

TheWebmen\ElementalGrid:
  defaultSizeField: 'MD'
  defaultOffsetField: 'MD'
  cssFramework: 'bootstrap'
