---
Name: elementalgrid
After:
  - 'elemental'
---
SilverStripe\Core\Manifest\ModuleManifest:
  module_priority:
    - wedevelopnl/silverstripe-elemental-grid
    - dnadesign/silverstripe-elemental

SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'wedevelopnl/silverstripe-elemental-grid:client/dist/js/bundle.js'
  extra_requirements_css:
    - 'wedevelopnl/silverstripe-elemental-grid:client/dist/styles/bundle.css'

DNADesign\Elemental\Models\ElementalArea:
  extensions:
    - WeDevelop\ElementalGrid\Extensions\ElementalAreaExtension

DNADesign\Elemental\Models\BaseElement:
  inline_editable: false
  extensions:
    - WeDevelop\ElementalGrid\Extensions\BaseElementExtension

DNADesign\Elemental\Models\ElementContent:
  controller_class: WeDevelop\ElementalGrid\Controllers\ElementContentController
  extensions:
    - WeDevelop\ElementalGrid\Extensions\ElementContentExtension

WeDevelop\ElementalGrid\ElementalConfig:
  default_viewport: 'MD'
  css_framework: 'bulma'
  enable_custom_title_classes: true
  default_title_tag: 'h2'
